name: 'Deploy App to S3'

#on: [push] #toutes les branches

on:
  push:
    branches:
      - gnagna #uniquement sur la branche main


jobs:
  deployement: # nom
    runs-on: ubuntu-latest # instance temps
    steps:
    - name: chekout code
      uses: actions/checkout@v4     

    - name: list directory
      run: |
        ls -la