name: 'Deploy App to S3'

#on: [push] # toutes les branches
# ou bien
#on:
  #push:
    #branches:
      #- main # uniquement sur la branche main

on:
  push:
    branches:
      - maBranch # uniquement sur la branche maBranch


jobs:
  deployment: # nom
    runs-on: ubuntu-latest # instance temporaire
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli

    - name: Configure AWS credentials
      run: |
        
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-west-3